### ISSUE TITLE
Feature request: Make StartServerAsync an instance method

### ISSUE THREAD

**Issue by IustinMicu** [davidfowl/FeatherHttp#1]
I had a look at the example from the Readme and I think it looks quite nice!
I also would like to propose a small change: Make the `StartServerAsync` an instance method.
This would simplify the API a bit and one could use it like this:
`var server = await app.StartServerAsync("http://localhost:3000");`.

**Comment by solev** [comment]
Great idea. I quickly done a PR on this:
#2

**Comment by davidfowl** [comment]
Thanks @solev
