### ISSUE TITLE
Create a template for feather that can be used with dotnet new

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/FeatherHttp#14]
We need some a single hello world template.

**Comment by RobotOptimist** [comment]
I've got something like that going now: https://github.com/RobotOptimist/featherhttp-template would you like a PR to this repo with that under a /templates or something like that?

**Comment by davidfowl** [comment]
Yes please! It should produce a nuget package with the template package type as well (see https://github.com/CarterCommunity/Carter/blob/5c07775e1cc44aeb65291ec0c7a559281c288696/template/CarterTemplate.nuspec#L19).

The name should be FeatherHttp.Templates

**Comment by RobotOptimist** [comment]
I'm really glad to have worked on this task! Thank you!

**Comment by davidfowl** [comment]
Done!
