### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by solev** [davidfowl/FeatherHttp#3]
Hey @davidfowl 
Do you have any future plans for this repo? Or is it just a showcase.
Tbh, it looks very interesting and cool to me, wanna help improve it if you have plans

**Comment by davidfowl** [comment]
I don't know yet, it's something I want to start a discussion about. Today ASP.NET Core needs to be hosted in something. We have the generic host and the web host. This sample is basically a mini host that removes that and just lets you write a server. Here are some of the currently broken things:

Other broken things:
- IIS doesn't work, it hardcodes kestrel (fixable but does it matter?)
- IHostedService doesn't work (also fixable)
- Default hosting diagnostics aren't enabled
- We don't provide an easy way to get the IWebHostEnvironment (you need to grab it from the ServiceProvider)

**Comment by davidfowl** [comment]
OK I re-wrote the thing to use more of the existing host features. Most things work now 😄

**Comment by AlexEyler** [comment]
Any plans for a nuget package?

**Comment by davidfowl** [comment]
Yes I plan to make a NuGet package once I stop changing the APIs 😬

**Comment by jr-araujo** [comment]
I would like to know if this project has the intention to be another alternative to Nancy Web Framework. I saw that the project is on its beginning, but what are the main purpose of this project?

I feel it should be an interesting opportunity to contribute to it!

**Comment by davidfowl** [comment]
> I would like to know if this project has the intention to be another alternative to Nancy Web Framework. I saw that the project is on its beginning, but what are the main purpose of this project?

Not quite. It's more about being an alternative set of APIs for wiring up ASP.NET Core middleware and routes directly. It uses 90% of ASP.NET Core and basically changes the Startup pattern to "cut the fat". That's why all existing ASP.NET Core frameworks continue to function (and why the framework fits in a single file)
